api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    collection:
        pagination:
            # To enable or disable pagination for all resource collections by default.
            enabled: false
