#doctrine:
#    dbal:
#        url: '%env(resolve:DATABASE_URL)%'

doctrine:
    dbal:

        types:
            point: App\Entity\PointType

        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                url: '%env(DATABASE_URL)%'
                mapping_types:
                    point: point
                    _text: string

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                ST_Point: App\DQL\ST_Point
                ST_AsText: App\DQL\ST_AsText
                ST_Distance_Sphere: App\DQL\ST_Distance_Sphere
        metadata_cache_driver: ~

        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool

        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool




